export const ProjectData = [
    {
        id: 1,
        slug: "netflix-clone",
        title: "Netflix Clone",
        shortDesc: "Full Stack Web Application",
        image: "/netflix-app.jpg",
        techStack: ["React", "Node JS", "Express JS", "MongoDB", "JWT", "NodeMailer", "TailwindCSS"],
        longDescription: "I built a full-stack Netflix clone using the MERN stack where users can register, log in, and browse movies and series. I implemented JWT authentication, email OTP verification with Nodemailer, and secure login/signup flows.The frontend was designed with React and Tailwind CSS for a responsive look. I also added an admin panel where users and movies can be managed through CRUD operations",
        features: [
            "User authentication with JWT",
            "Email based OTP Verification",
            "Movies listing & Searching Movies",
            "Responsive UI",
        ],
        link: "https://github.com/sipu-git/netflix_frontend",

    },
    {
        id: 2,
        slug: "e-commerce",
        title: "E-Commerce",
        shortDesc: "Full Stack Web Application",
        image: "/flipkart.jpg",
        techStack: ["React", "Node JS", "Express JS", "MongoDB", "JWT", "NodeMailer", "TailwindCSS"],
        longDescription: "A complete e-commerce platform with product listing, cart, checkout, and payment integration.",
        features: [
            "Product management",
            "Add To Cart",
            "User Profile Management",
        ],
        link: "https://github.com/yourname/netflix-clone",
    },
    {
        id: 3,
        slug: "todo-list",
        title: "TODO List Application",
        shortDesc: "Full Stack Web Application",
        image: "/todo-list.jpg",
        techStack: ["MongoDB", "Express js", "Next js", "TypeScript", "Tailwind CSS", "JWT", "Cookies-parser",
            "Cloudinary"],
        longDescription: "This is a full-stack Todo app where users can create, edit, and delete their tasks. I built the backend using Node.js and Express with MongoDB Atlas for data storage. JWT and cookies were used for authenticationand session handling. The frontend was developed using Next.js with TypeScript for better structure andtype safety. I also integrated Cloudinary for media uploads and used modern UI libraries like shadcn/uiand framer-motion to make it more interactive.",
        features: [
            "Responsive UI",
            "Animated Landing Page",
            "Cookies based Data backup",
            "CRUD Operation for task management",
            "User Profile management",
        ],
        link: "https://todo-frontend-delta-seven.vercel.app",
    },
    {
        id: 4,
        slug: "aws-rds-node-backend",
        title: "AWS RDS Integated Nodejs Application",
        shortDesc: "Node.js Backend with AWS RDS & REST APIs",
        image: "/todo-list.jpg",
        techStack: [
            "Node.js",
            "Express.js",
            "AWS RDS",
            "AWS EC2",
            "MySQL",
            "mysql2",
            "PM2",
            "WinSCP",
        ],
        longDescription: "This project is a production-ready backend application built using Node.js and Express,integrated with AWS RDS for managed relational database storage. The application exposes secure REST APIs for CRUD operations, authentication, and role-based access control.",
        features: [
            "RESTful API design using Express.js",
            "AWS RDS integration for managed database",
            "AWS EC2 instance creation for running the Database",
            "Secure environment variable management",
            "AWS RDS Connection with Mysql Workbench",
            "Optimized SQL queries for performance",
        ],
        architecture: [
            "Client → REST API (Node.js)",
            "Node.js → AWS RDS (Private DB)",
            "PM2 for process management",
        ],
        link: "https://github.com/sipu-git/aws-backend",
    }
]